let arrayDeSeries = [
    /*SERIES DE AUTOS--------------------------------------------*/
    {
        "href":'../pages/detalleSerie.html',
        "portada":'../assets/images/serie5.jpg',
        "titulo":'formula 1',
        "categoria":'autos',
        "tipo":'serie',
    },
    {
        "href":'../pages/detalleSerie.html',
        "portada":'../assets/images/serie14.jpg',
        "titulo":'un gran viaje por europa',
        "categoria":'autos',
        "tipo":'serie',
    },
    {
        "href":'../pages/detalleSerie.html',
        "portada":'../assets/images/serie15.jpg',
        "titulo":'race bubba wallace',
        "categoria":'autos',
        "tipo":'serie',
    },
    {
        "href":'../pages/detalleSerie.html',
        "portada":'../assets/images/serie16.jpg',
        "titulo":'west coast customs',
        "categoria":'autos',
        "tipo":'serie',
    },
    /*SERIES De CIENCIA FICCION--------------------------------------*/
    {
        "href":'../pages/detalleSerie.html',
        "portada":'../assets/images/serie17.jpg',
        "titulo":'outlander',
        "categoria":'cienciaFiccion',
        "tipo":'serie',
    },
    {
        "href":'../pages/detalleSerie.html',
        "portada":'../assets/images/serie18.jpg',
        "titulo":'flash',
        "categoria":'cienciaFiccion',
        "tipo":'serie',
    },
    {
        "href":'../pages/detalleSerie.html',
        "portada":'../assets/images/serie19.jpg',
        "titulo":'avatar',
        "categoria":'cienciaFiccion',
        "tipo":'serie',
    },
    {
        "href":'../pages/detalleSerie.html',
        "portada":'../assets/images/serie1.jpg',
        "titulo":'breaking bad',
        "categoria":'cienciaFiccion',
        "tipo":'serie',
    },
    /*SERIES DE COMEDIA--------------------------------------*/
    {
        "href":'../pages/detalleSerie.html',
        "portada":'../assets/images/serie6.jpg',
        "titulo":'casados con hijos',
        "categoria":'comedia',
        "tipo":'serie',
    },
    {
        "href":'../pages/detalleSerie.html',
        "portada":'../assets/images/serie7.jpg',
        "titulo":'the office',
        "categoria":'comedia',
        "tipo":'serie',
    },
    {
        "href":'../pages/detalleSerie.html',
        "portada":'../assets/images/serie8.jpg',
        "titulo":'seinfeld',
        "categoria":'comedia',
        "tipo":'serie',
    },
    {
        "href":'../pages/detalleSerie.html',
        "portada":'../assets/images/serie9.jpg',
        "titulo":'un show mas',
        "categoria":'comedia',
        "tipo":'serie',
    },
    /*SERIES DE TERROR--------------------------------------*/
    {
        "href":'../pages/detalleSerie.html',
        "portada":'../assets/images/serie10.jpg',
        "titulo":'true blood',
        "categoria":'terror',
        "tipo":'serie',
    },
    {
        "href":'../pages/detalleSerie.html',
        "portada":'../assets/images/serie11.jpg',
        "titulo":'parasyte',
        "categoria":'terror',
        "tipo":'serie',
    },
    {
        "href":'../pages/detalleSerie.html',
        "portada":'../assets/images/serie12.jpg',
        "titulo":'slasher',
        "categoria":'terror',
        "tipo":'serie',
    },
    {
        "href":'../pages/detalleSerie.html',
        "portada":'../assets/images/serie13.jpg',
        "titulo":'the walking dead',
        "categoria":'terror',
        "tipo":'serie',
    },
    /*SERIES DE SUSPENSO--------------------------------------*/
    {
        "href":'../pages/detalleSerie.html',
        "portada":'../assets/images/serie3.jpg',
        "titulo":'gossip girl',
        "categoria":'suspenso',
        "tipo":'serie',
    },
    {
        "href":'../pages/detalleSerie.html',
        "portada":'../assets/images/serie2.jpg',
        "titulo":'pablo escobar',
        "categoria":'suspenso',
        "tipo":'serie',
    },
    {
        "href":'../pages/detalleSerie.html',
        "portada":'../assets/images/serie20.jpg',
        "titulo":'la ley y el orden',
        "categoria":'suspenso',
        "tipo":'serie',
    },
    {
        "href":'../pages/detalleSerie.html',
        "portada":'../assets/images/serie21.jpg',
        "titulo":'csi',
        "categoria":'suspenso',
        "tipo":'serie',
    }, 
]